apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: heptio-contour
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: ratelimit
  type: ClusterIP